# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jeppe/Documents/projekt/CNNWine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jeppe/Documents/projekt/CNNWine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeppe/Documents/projekt/CNNWine/CMakeFiles /home/jeppe/Documents/projekt/CNNWine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeppe/Documents/projekt/CNNWine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NNMLP

# Build rule for target.
NNMLP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NNMLP
.PHONY : NNMLP

# fast build rule for target.
NNMLP/fast:
	$(MAKE) -f CMakeFiles/NNMLP.dir/build.make CMakeFiles/NNMLP.dir/build
.PHONY : NNMLP/fast

#=============================================================================
# Target rules for targets named RCEnet

# Build rule for target.
RCEnet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RCEnet
.PHONY : RCEnet

# fast build rule for target.
RCEnet/fast:
	$(MAKE) -f CMakeFiles/RCEnet.dir/build.make CMakeFiles/RCEnet.dir/build
.PHONY : RCEnet/fast

NNMLP.o: NNMLP.cpp.o

.PHONY : NNMLP.o

# target to build an object file
NNMLP.cpp.o:
	$(MAKE) -f CMakeFiles/NNMLP.dir/build.make CMakeFiles/NNMLP.dir/NNMLP.cpp.o
.PHONY : NNMLP.cpp.o

NNMLP.i: NNMLP.cpp.i

.PHONY : NNMLP.i

# target to preprocess a source file
NNMLP.cpp.i:
	$(MAKE) -f CMakeFiles/NNMLP.dir/build.make CMakeFiles/NNMLP.dir/NNMLP.cpp.i
.PHONY : NNMLP.cpp.i

NNMLP.s: NNMLP.cpp.s

.PHONY : NNMLP.s

# target to generate assembly for a file
NNMLP.cpp.s:
	$(MAKE) -f CMakeFiles/NNMLP.dir/build.make CMakeFiles/NNMLP.dir/NNMLP.cpp.s
.PHONY : NNMLP.cpp.s

RCEnet.o: RCEnet.cpp.o

.PHONY : RCEnet.o

# target to build an object file
RCEnet.cpp.o:
	$(MAKE) -f CMakeFiles/RCEnet.dir/build.make CMakeFiles/RCEnet.dir/RCEnet.cpp.o
.PHONY : RCEnet.cpp.o

RCEnet.i: RCEnet.cpp.i

.PHONY : RCEnet.i

# target to preprocess a source file
RCEnet.cpp.i:
	$(MAKE) -f CMakeFiles/RCEnet.dir/build.make CMakeFiles/RCEnet.dir/RCEnet.cpp.i
.PHONY : RCEnet.cpp.i

RCEnet.s: RCEnet.cpp.s

.PHONY : RCEnet.s

# target to generate assembly for a file
RCEnet.cpp.s:
	$(MAKE) -f CMakeFiles/RCEnet.dir/build.make CMakeFiles/RCEnet.dir/RCEnet.cpp.s
.PHONY : RCEnet.cpp.s

matlib.o: matlib.cpp.o

.PHONY : matlib.o

# target to build an object file
matlib.cpp.o:
	$(MAKE) -f CMakeFiles/NNMLP.dir/build.make CMakeFiles/NNMLP.dir/matlib.cpp.o
	$(MAKE) -f CMakeFiles/RCEnet.dir/build.make CMakeFiles/RCEnet.dir/matlib.cpp.o
.PHONY : matlib.cpp.o

matlib.i: matlib.cpp.i

.PHONY : matlib.i

# target to preprocess a source file
matlib.cpp.i:
	$(MAKE) -f CMakeFiles/NNMLP.dir/build.make CMakeFiles/NNMLP.dir/matlib.cpp.i
	$(MAKE) -f CMakeFiles/RCEnet.dir/build.make CMakeFiles/RCEnet.dir/matlib.cpp.i
.PHONY : matlib.cpp.i

matlib.s: matlib.cpp.s

.PHONY : matlib.s

# target to generate assembly for a file
matlib.cpp.s:
	$(MAKE) -f CMakeFiles/NNMLP.dir/build.make CMakeFiles/NNMLP.dir/matlib.cpp.s
	$(MAKE) -f CMakeFiles/RCEnet.dir/build.make CMakeFiles/RCEnet.dir/matlib.cpp.s
.PHONY : matlib.cpp.s

neu.o: neu.cpp.o

.PHONY : neu.o

# target to build an object file
neu.cpp.o:
	$(MAKE) -f CMakeFiles/NNMLP.dir/build.make CMakeFiles/NNMLP.dir/neu.cpp.o
	$(MAKE) -f CMakeFiles/RCEnet.dir/build.make CMakeFiles/RCEnet.dir/neu.cpp.o
.PHONY : neu.cpp.o

neu.i: neu.cpp.i

.PHONY : neu.i

# target to preprocess a source file
neu.cpp.i:
	$(MAKE) -f CMakeFiles/NNMLP.dir/build.make CMakeFiles/NNMLP.dir/neu.cpp.i
	$(MAKE) -f CMakeFiles/RCEnet.dir/build.make CMakeFiles/RCEnet.dir/neu.cpp.i
.PHONY : neu.cpp.i

neu.s: neu.cpp.s

.PHONY : neu.s

# target to generate assembly for a file
neu.cpp.s:
	$(MAKE) -f CMakeFiles/NNMLP.dir/build.make CMakeFiles/NNMLP.dir/neu.cpp.s
	$(MAKE) -f CMakeFiles/RCEnet.dir/build.make CMakeFiles/RCEnet.dir/neu.cpp.s
.PHONY : neu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... NNMLP"
	@echo "... rebuild_cache"
	@echo "... RCEnet"
	@echo "... NNMLP.o"
	@echo "... NNMLP.i"
	@echo "... NNMLP.s"
	@echo "... RCEnet.o"
	@echo "... RCEnet.i"
	@echo "... RCEnet.s"
	@echo "... matlib.o"
	@echo "... matlib.i"
	@echo "... matlib.s"
	@echo "... neu.o"
	@echo "... neu.i"
	@echo "... neu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

